# Generated by Django 2.2.2 on 2019-06-17 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 10, 48, 39, 146025, tzinfo=utc), verbose_name='Время создания')),
                ('name', models.CharField(max_length=128, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название покупки')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название продукта / предмета')),
                ('is_buy', models.BooleanField(default=False, verbose_name='Куплено')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notepad.Purchase', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Список продуктов / предметов',
                'verbose_name_plural': 'Списки продуктов / предметов',
                'ordering': ['name'],
            },
        ),
    ]
