# Generated by Django 2.2.2 on 2019-06-17 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 15, 40, 2, 600995, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
