# Generated by Django 2.2.2 on 2019-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0004_auto_20190623_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
